export const APPLICATION_LIST_REQUEST = 'APPLICATION_LIST_REQUEST'
export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS'
export const APPLICATION_LIST_FAIL = 'APPLICATION_LIST_FAIL'

export const APPLICATION_DETAILS_REQUEST = 'APPLICATION_DETAILS_REQUEST'
export const APPLICATION_DETAILS_SUCCESS = 'APPLICATION_DETAILS_SUCCESS'
export const APPLICATION_DETAILS_FAIL = 'APPLICATION_DETAILS_FAIL'

export const APPLICATION_UPDATE_REQUEST = 'APPLICATION_UPDATE_REQUEST'
export const APPLICATION_UPDATE_SUCCESS = 'APPLICATION_UPDATE_SUCCESS'
export const APPLICATION_UPDATE_FAIL = 'APPLICATION_UPDATE_FAIL'

export const APPLICATION_RESET_KEY_REQUEST = 'APPLICATION_RESET_KEY_REQUEST'
export const APPLICATION_RESET_KEY_SUCCESS = 'APPLICATION_RESET_KEY_SUCCESS'
export const APPLICATION_RESET_KEY_FAIL = 'APPLICATION_RESET_KEY_FAIL'

export const APPLICATION_CREATE_REQUEST = 'APPLICATION_CREATE_REQUEST'
export const APPLICATION_CREATE_SUCCESS = 'APPLCIATION_CREATE_SUCCESS'
export const APPLICATION_CREATE_FAIL = 'APPLICATION_CREATE_FAIL'


