export const APPLICATION_LIST_REQUEST = 'APPLICATION_LIST_REQUEST'
export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS'
export const APPLICATION_LIST_FAIL = 'APPLICATION_LIST_FAIL'

export const APPLICATION_DETAILS_REQUEST = 'APPLICATION_DETAILS_REQUEST'
export const APPLICATION_DETAILS_SUCCESS = 'APPLICATION_DETAILS_SUCCESS'
export const APPLICATION_DETAILS_FAIL = 'APPLICATION_DETAILS_FAIL'

export const APPLICATION_UPDATE_REQUEST = 'APPLICATION_UPDATE_REQUEST'
export const APPLICATION_UPDATE_SUCCESS = 'APPLICATION_UPDATE_SUCCESS'
export const APPLICATION_UPDATE_FAILURE = 'APPLICATION_UPDATE_FAILURE'
